INSERT INTO MATERIALI(IDMATERIALE,CODICE,DESCRIZIONE,PREZIOSO,PESOSPECIFICO,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA)VALUES(-1,' N/D ','** NESSUN MATERIALE','N',0,'N',SYSDATE,'IMPIANTO');
INSERT INTO MATERIALI(IDMATERIALE,CODICE,DESCRIZIONE,PREZIOSO,PESOSPECIFICO,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA)VALUES(NULL,'AU','ORO','S',1.8,'N',SYSDATE,'IMPIANTO');
INSERT INTO MATERIALI(IDMATERIALE,CODICE,DESCRIZIONE,PREZIOSO,PESOSPECIFICO,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA)VALUES(NULL,'CU','RAME','N',0,'N',SYSDATE,'IMPIANTO');
INSERT INTO MATERIALI(IDMATERIALE,CODICE,DESCRIZIONE,PREZIOSO,PESOSPECIFICO,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA)VALUES(NULL,'BRO','BRONZO','N',0,'N',SYSDATE,'IMPIANTO');
INSERT INTO MATERIALI(IDMATERIALE,CODICE,DESCRIZIONE,PREZIOSO,PESOSPECIFICO,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA)VALUES(NULL,'NI','NICHEL','N',0,'N',SYSDATE,'IMPIANTO');
INSERT INTO MATERIALI(IDMATERIALE,CODICE,DESCRIZIONE,PREZIOSO,PESOSPECIFICO,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA)VALUES(NULL,'CR','CROMO','S',0,'N',SYSDATE,'IMPIANTO');
INSERT INTO MATERIALI(IDMATERIALE,CODICE,DESCRIZIONE,PREZIOSO,PESOSPECIFICO,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA)VALUES(NULL,'PD','PALLADIO','S',0,'N',SYSDATE,'IMPIANTO');
INSERT INTO MATERIALI(IDMATERIALE,CODICE,DESCRIZIONE,PREZIOSO,PESOSPECIFICO,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA)VALUES(NULL,'RU','RUTENIO','S',0,'N',SYSDATE,'IMPIANTO');
INSERT INTO MATERIALI(IDMATERIALE,CODICE,DESCRIZIONE,PREZIOSO,PESOSPECIFICO,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA)VALUES(NULL,'AG','ARGENTO','S',0,'N',SYSDATE,'IMPIANTO');
INSERT INTO MATERIALI(IDMATERIALE,CODICE,DESCRIZIONE,PREZIOSO,PESOSPECIFICO,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA)VALUES(NULL,'OTT','OTTONE','N',0,'N',SYSDATE,'IMPIANTO');

commit;

INSERT INTO TIPIDOCUMENTO(IDTIPODOCUMENTO,DESCRIZIONE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'DOCUEMNTO WORD','N',SYSDATE,'IMPIANTO');
INSERT INTO TIPIDOCUMENTO(IDTIPODOCUMENTO,DESCRIZIONE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'DOCUEMNTO EXCEL','N',SYSDATE,'IMPIANTO');
INSERT INTO TIPIDOCUMENTO(IDTIPODOCUMENTO,DESCRIZIONE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'IMMAGINE JPG','N',SYSDATE,'IMPIANTO');
INSERT INTO TIPIDOCUMENTO(IDTIPODOCUMENTO,DESCRIZIONE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'DOCUEMNTO GIF','N',SYSDATE,'IMPIANTO');
COMMIT;


INSERT INTO IMPIANTI(IDIMPIANTO,DESCRIZIONE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'GALVANICA AUTOMATICA','N',SYSDATE,'IMPIANTO');
INSERT INTO IMPIANTI(IDIMPIANTO,DESCRIZIONE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'GALVANICA MANUALE','N',SYSDATE,'IMPIANTO');
INSERT INTO IMPIANTI(IDIMPIANTO,DESCRIZIONE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'GALVANICA ROTO','N',SYSDATE,'IMPIANTO');
COMMIT;



INSERT INTO VASCHE(IDVASCA,DESCRIZIONEBREVE,DESCRIZIONE,ABILITASTRATO,IDIMPIANTO,IDMATERIALE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA)VALUES(NULL,'RAME ALCALINO','RAME ALCALINO','S',1,2,'N',SYSDATE,'IMPIANTO');
INSERT INTO VASCHE(IDVASCA,DESCRIZIONEBREVE,DESCRIZIONE,ABILITASTRATO,IDIMPIANTO,IDMATERIALE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA)VALUES(NULL,'RAME ACIDO','RAME ACIDO','S',1,2,'N',SYSDATE,'IMPIANTO');
INSERT INTO VASCHE(IDVASCA,DESCRIZIONEBREVE,DESCRIZIONE,ABILITASTRATO,IDIMPIANTO,IDMATERIALE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA)VALUES(NULL,'BRONZO','BRONZO','S',1,3,'N',SYSDATE,'IMPIANTO');
INSERT INTO VASCHE(IDVASCA,DESCRIZIONEBREVE,DESCRIZIONE,ABILITASTRATO,IDIMPIANTO,IDMATERIALE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA)VALUES(NULL,'NICHEL LUCIDO','NICHEL LUCIDO','S',1,4,'N',SYSDATE,'IMPIANTO');
INSERT INTO VASCHE(IDVASCA,DESCRIZIONEBREVE,DESCRIZIONE,ABILITASTRATO,IDIMPIANTO,IDMATERIALE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA)VALUES(NULL,'NICHEL OPACO','NICHEL OPACO','S',1,4,'N',SYSDATE,'IMPIANTO');
INSERT INTO VASCHE(IDVASCA,DESCRIZIONEBREVE,DESCRIZIONE,ABILITASTRATO,IDIMPIANTO,IDMATERIALE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA)VALUES(NULL,'NICHEL PERLA','NICHEL PERLA','S',1,4,'N',SYSDATE,'IMPIANTO');
INSERT INTO VASCHE(IDVASCA,DESCRIZIONEBREVE,DESCRIZIONE,ABILITASTRATO,IDIMPIANTO,IDMATERIALE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA)VALUES(NULL,'NICHEL FOSFORO','NICHEL FOSFORO','S',1,4,'N',SYSDATE,'IMPIANTO');
INSERT INTO VASCHE(IDVASCA,DESCRIZIONEBREVE,DESCRIZIONE,ABILITASTRATO,IDIMPIANTO,IDMATERIALE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA)VALUES(NULL,'CROMO','CROMO','S',1,5,'N',SYSDATE,'IMPIANTO');
INSERT INTO VASCHE(IDVASCA,DESCRIZIONEBREVE,DESCRIZIONE,ABILITASTRATO,IDIMPIANTO,IDMATERIALE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA)VALUES(NULL,'DEKRO','DEKRO','N',1,-1,'N',SYSDATE,'IMPIANTO');
INSERT INTO VASCHE(IDVASCA,DESCRIZIONEBREVE,DESCRIZIONE,ABILITASTRATO,IDIMPIANTO,IDMATERIALE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA)VALUES(NULL,'CEMENTAZIONE','CEMENTAZIONE','N',1,-1,'N',SYSDATE,'IMPIANTO');
INSERT INTO VASCHE(IDVASCA,DESCRIZIONEBREVE,DESCRIZIONE,ABILITASTRATO,IDIMPIANTO,IDMATERIALE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA)VALUES(NULL,'PALLADIO','PALLADIO','S',1,6,'N',SYSDATE,'IMPIANTO');
INSERT INTO VASCHE(IDVASCA,DESCRIZIONEBREVE,DESCRIZIONE,ABILITASTRATO,IDIMPIANTO,IDMATERIALE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA)VALUES(NULL,'PALLADIO NICHEL','PALLADIO NICHEL','S',1,6,'N',SYSDATE,'IMPIANTO');
INSERT INTO VASCHE(IDVASCA,DESCRIZIONEBREVE,DESCRIZIONE,ABILITASTRATO,IDIMPIANTO,IDMATERIALE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA)VALUES(NULL,'PALLADIO NERO','PALLADIO NERO','S',1,6,'N',SYSDATE,'IMPIANTO');
INSERT INTO VASCHE(IDVASCA,DESCRIZIONEBREVE,DESCRIZIONE,ABILITASTRATO,IDIMPIANTO,IDMATERIALE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA)VALUES(NULL,'RUTENIO','RUTENIO','S',1,7,'N',SYSDATE,'IMPIANTO');
INSERT INTO VASCHE(IDVASCA,DESCRIZIONEBREVE,DESCRIZIONE,ABILITASTRATO,IDIMPIANTO,IDMATERIALE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA)VALUES(NULL,'ARGENTO','ARGENTO','S',1,8,'N',SYSDATE,'IMPIANTO');
INSERT INTO VASCHE(IDVASCA,DESCRIZIONEBREVE,DESCRIZIONE,ABILITASTRATO,IDIMPIANTO,IDMATERIALE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA)VALUES(NULL,'OTTONE','OTTONE','S',1,9,'N',SYSDATE,'IMPIANTO');
INSERT INTO VASCHE(IDVASCA,DESCRIZIONEBREVE,DESCRIZIONE,ABILITASTRATO,IDIMPIANTO,IDMATERIALE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA)VALUES(NULL,'ORO FERRO','ORO FERRO','S',1,1,'N',SYSDATE,'IMPIANTO');
INSERT INTO VASCHE(IDVASCA,DESCRIZIONEBREVE,DESCRIZIONE,ABILITASTRATO,IDIMPIANTO,IDMATERIALE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA)VALUES(NULL,'ORO COBALTO','ORO COBALTO','S',1,1,'N',SYSDATE,'IMPIANTO');
INSERT INTO VASCHE(IDVASCA,DESCRIZIONEBREVE,DESCRIZIONE,ABILITASTRATO,IDIMPIANTO,IDMATERIALE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA)VALUES(NULL,'ORO 1N','ORO 1N','S',1,1,'N',SYSDATE,'IMPIANTO');
INSERT INTO VASCHE(IDVASCA,DESCRIZIONEBREVE,DESCRIZIONE,ABILITASTRATO,IDIMPIANTO,IDMATERIALE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA)VALUES(NULL,'ORO 53','ORO 53','S',1,1,'N',SYSDATE,'IMPIANTO');
INSERT INTO VASCHE(IDVASCA,DESCRIZIONEBREVE,DESCRIZIONE,ABILITASTRATO,IDIMPIANTO,IDMATERIALE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA)VALUES(NULL,'ORO 05','ORO 05','S',1,1,'N',SYSDATE,'IMPIANTO');
INSERT INTO VASCHE(IDVASCA,DESCRIZIONEBREVE,DESCRIZIONE,ABILITASTRATO,IDIMPIANTO,IDMATERIALE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA)VALUES(NULL,'ORO INDIO','ORO INDIO','S',1,1,'N',SYSDATE,'IMPIANTO');
INSERT INTO VASCHE(IDVASCA,DESCRIZIONEBREVE,DESCRIZIONE,ABILITASTRATO,IDIMPIANTO,IDMATERIALE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA)VALUES(NULL,'ORO ACIDO','ORO ACIDO','S',1,1,'N',SYSDATE,'IMPIANTO');
INSERT INTO VASCHE(IDVASCA,DESCRIZIONEBREVE,DESCRIZIONE,ABILITASTRATO,IDIMPIANTO,IDMATERIALE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA)VALUES(NULL,'ORO NERO','ORO NERO','S',1,1,'N',SYSDATE,'IMPIANTO');
commit;
