Insert into MENU (IDMENU,IDMENUPADRE,ETICHETTA,DESCRIZIONE,ONCLICK,HREF,FONT,AZIONE,SEQUENZA) values ('1',null,'ACCOUNT','GESTIONE ACCOUNT E ABILITAZIONI',null,null,'fa fa-user fa-lg',NULL,'1');
Insert into MENU (IDMENU,IDMENUPADRE,ETICHETTA,DESCRIZIONE,ONCLICK,HREF,FONT,AZIONE,SEQUENZA) values ('2','1','ABILITA MENU','ABILITA ACCOUNT AL MENU',null,'/ACCOUNT/ABILITAMENU','',NULL,'2');
Insert into MENU (IDMENU,IDMENUPADRE,ETICHETTA,DESCRIZIONE,ONCLICK,HREF,FONT,AZIONE,SEQUENZA) values ('3','2','CREA ACCOUNT','crea un nuovo account',null,'/ACCOUNT/CREANUOVOACCOUNT','','A','3');
Insert into MENU (IDMENU,IDMENUPADRE,ETICHETTA,DESCRIZIONE,ONCLICK,HREF,FONT,AZIONE,SEQUENZA) values ('4','2','RIMUOVI ACCOUNT','rimuove un account',null,'/ACCOUNT/RIMUOVIACCOUNT','','A','3');

