

INSERT INTO BRAND(IDBRAND,BRAND,CODICEGESTIONALE,PREFISSOCOLORE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'BALENCIAGA','BALENCIAGA','BA','N',SYSDATE,'IMPIANTO');
INSERT INTO BRAND(IDBRAND,BRAND,CODICEGESTIONALE,PREFISSOCOLORE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'BOTTEGA VENETA','BOTTEGAV','BV','N',SYSDATE,'IMPIANTO');
INSERT INTO BRAND(IDBRAND,BRAND,CODICEGESTIONALE,PREFISSOCOLORE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'CHANEL','CHANEL','CH','N',SYSDATE,'IMPIANTO');
INSERT INTO BRAND(IDBRAND,BRAND,CODICEGESTIONALE,PREFISSOCOLORE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'DOLCE GABBANA','DEG','DG','N',SYSDATE,'IMPIANTO');
INSERT INTO BRAND(IDBRAND,BRAND,CODICEGESTIONALE,PREFISSOCOLORE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'FENDI','FENDI','FE','N',SYSDATE,'IMPIANTO');
INSERT INTO BRAND(IDBRAND,BRAND,CODICEGESTIONALE,PREFISSOCOLORE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'GUCCI','GUCCI','GU','N',SYSDATE,'IMPIANTO');
INSERT INTO BRAND(IDBRAND,BRAND,CODICEGESTIONALE,PREFISSOCOLORE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'LE JEUNES ETOILES','LJE','LJ','N',SYSDATE,'IMPIANTO');
INSERT INTO BRAND(IDBRAND,BRAND,CODICEGESTIONALE,PREFISSOCOLORE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'LOUIS VUITTON','LOUISV','LV','N',SYSDATE,'IMPIANTO');
INSERT INTO BRAND(IDBRAND,BRAND,CODICEGESTIONALE,PREFISSOCOLORE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'MCQUEEN','MCQUEEN','MQ','N',SYSDATE,'IMPIANTO');
INSERT INTO BRAND(IDBRAND,BRAND,CODICEGESTIONALE,PREFISSOCOLORE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'YSL','YSL','YS','N',SYSDATE,'IMPIANTO');
INSERT INTO BRAND(IDBRAND,BRAND,CODICEGESTIONALE,PREFISSOCOLORE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'CELINE','CELINE','CE','N',SYSDATE,'IMPIANTO');
INSERT INTO BRAND(IDBRAND,BRAND,CODICEGESTIONALE,PREFISSOCOLORE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'MAMI','MAMI','MA','N',SYSDATE,'IMPIANTO');
INSERT INTO BRAND(IDBRAND,BRAND,CODICEGESTIONALE,PREFISSOCOLORE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'RICHMOND','RICHMOND','XX','N',SYSDATE,'IMPIANTO');
INSERT INTO BRAND(IDBRAND,BRAND,CODICEGESTIONALE,PREFISSOCOLORE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'DA DEFINIRE','.','XX','N',SYSDATE,'IMPIANTO');
INSERT INTO BRAND(IDBRAND,BRAND,CODICEGESTIONALE,PREFISSOCOLORE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'YSL PARIGI','YSL PARIGI','YP','N',SYSDATE,'IMPIANTO');
INSERT INTO BRAND(IDBRAND,BRAND,CODICEGESTIONALE,PREFISSOCOLORE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'ELEN','ELEN','XX','N',SYSDATE,'IMPIANTO');
INSERT INTO BRAND(IDBRAND,BRAND,CODICEGESTIONALE,PREFISSOCOLORE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'OWENSCORP','OWENSCORP','XX','N',SYSDATE,'IMPIANTO');
INSERT INTO BRAND(IDBRAND,BRAND,CODICEGESTIONALE,PREFISSOCOLORE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'PURALUCE','PURALUCE','XX','N',SYSDATE,'IMPIANTO');
INSERT INTO BRAND(IDBRAND,BRAND,CODICEGESTIONALE,PREFISSOCOLORE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'RIRI','RIRI','XX','N',SYSDATE,'IMPIANTO');
INSERT INTO BRAND(IDBRAND,BRAND,CODICEGESTIONALE,PREFISSOCOLORE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'CLIENTI VARI GREZZO','VARI GREZ','XX','N',SYSDATE,'IMPIANTO');
INSERT INTO BRAND(IDBRAND,BRAND,CODICEGESTIONALE,PREFISSOCOLORE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'BRAGANTI','BRAGANTI','XX','N',SYSDATE,'IMPIANTO');
INSERT INTO BRAND(IDBRAND,BRAND,CODICEGESTIONALE,PREFISSOCOLORE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'ALCE','ALCE','XX','N',SYSDATE,'IMPIANTO');



-- VECCHIA CODIFICA USATA PER COLORI IN PRIMO IMPIANTO
INSERT INTO BRAND(IDBRAND,BRAND,CODICEGESTIONALE,PREFISSOCOLORE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'BALENCIAGA',NULL,'BA','N',SYSDATE,'IMPIANTO');
INSERT INTO BRAND(IDBRAND,BRAND,CODICEGESTIONALE,PREFISSOCOLORE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'BOTTEGA VENETA',NULL,'BV','N',SYSDATE,'IMPIANTO');
INSERT INTO BRAND(IDBRAND,BRAND,CODICEGESTIONALE,PREFISSOCOLORE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'CHANEL',NULL,'CH','N',SYSDATE,'IMPIANTO');
INSERT INTO BRAND(IDBRAND,BRAND,CODICEGESTIONALE,PREFISSOCOLORE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'DOLCE GABBANA',NULL,'DG','N',SYSDATE,'IMPIANTO');
INSERT INTO BRAND(IDBRAND,BRAND,CODICEGESTIONALE,PREFISSOCOLORE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'FENDI',NULL,'FE','N',SYSDATE,'IMPIANTO');
INSERT INTO BRAND(IDBRAND,BRAND,CODICEGESTIONALE,PREFISSOCOLORE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'GUCCI',NULL,'GU','N',SYSDATE,'IMPIANTO');
INSERT INTO BRAND(IDBRAND,BRAND,CODICEGESTIONALE,PREFISSOCOLORE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'LE JEUNES ETOILES',NULL,'LJ','N',SYSDATE,'IMPIANTO');
INSERT INTO BRAND(IDBRAND,BRAND,CODICEGESTIONALE,PREFISSOCOLORE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'GUCCI',NULL,'GU','N',SYSDATE,'IMPIANTO');
INSERT INTO BRAND(IDBRAND,BRAND,CODICEGESTIONALE,PREFISSOCOLORE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'LUIS VUITTON',NULL,'LV','N',SYSDATE,'IMPIANTO');
INSERT INTO BRAND(IDBRAND,BRAND,CODICEGESTIONALE,PREFISSOCOLORE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'MC QUEEN',NULL,'MQ','N',SYSDATE,'IMPIANTO');
INSERT INTO BRAND(IDBRAND,BRAND,CODICEGESTIONALE,PREFISSOCOLORE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'YVES SAINT LAURENT',NULL,'YS','N',SYSDATE,'IMPIANTO');
INSERT INTO BRAND(IDBRAND,BRAND,CODICEGESTIONALE,PREFISSOCOLORE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'CELINE',NULL,'CE','N',SYSDATE,'IMPIANTO');
INSERT INTO BRAND(IDBRAND,BRAND,CODICEGESTIONALE,PREFISSOCOLORE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'MAMI',NULL,'MA','N',SYSDATE,'IMPIANTO');
INSERT INTO BRAND(IDBRAND,BRAND,CODICEGESTIONALE,PREFISSOCOLORE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'MONTBLANC',NULL,'MO','N',SYSDATE,'IMPIANTO');
INSERT INTO BRAND(IDBRAND,BRAND,CODICEGESTIONALE,PREFISSOCOLORE,CANCELLATO,DATAMODIFICA,UTENTEMODIFICA) VALUES (NULL,'VARI',NULL,'XX','N',SYSDATE,'IMPIANTO');