-- MANU ACCOUNT - GESTIONE SICUREZZA
Insert into MENU (IDMENU,IDMENUPADRE,ETICHETTA,DESCRIZIONE,ONCLICK,HREF,FONT,AZIONE,SEQUENZA) values ('1',null,'ACCOUNT','GESTIONE ACCOUNT E ABILITAZIONI',null,null,'fa fa-user fa-lg',NULL,'1');
Insert into MENU (IDMENU,IDMENUPADRE,ETICHETTA,DESCRIZIONE,ONCLICK,HREF,FONT,AZIONE,SEQUENZA) values ('2','1','ABILITA MENU','ABILITA ACCOUNT AL MENU',null,'/ACCOUNT/ABILITAMENU','',NULL,'2');
Insert into MENU (IDMENU,IDMENUPADRE,ETICHETTA,DESCRIZIONE,ONCLICK,HREF,FONT,AZIONE,SEQUENZA) values ('3','2','CREA ACCOUNT','crea un nuovo account',null,'/ACCOUNT/CREANUOVOACCOUNT','','A','3');
Insert into MENU (IDMENU,IDMENUPADRE,ETICHETTA,DESCRIZIONE,ONCLICK,HREF,FONT,AZIONE,SEQUENZA) values ('4','2','RIMUOVI ACCOUNT','rimuove un account',null,'/ACCOUNT/RIMUOVIACCOUNT','','A','4');

-- MENU ANAGRAFICA
Insert into MENU (IDMENU,IDMENUPADRE,ETICHETTA,DESCRIZIONE,ONCLICK,HREF,FONT,AZIONE,SEQUENZA) values ('10',null,'ANAGRAFICA','GESTIONE TABELLE ANAGRAFICA',null,null,'fa fa-table fa-lg',NULL,'10');
Insert into MENU (IDMENU,IDMENUPADRE,ETICHETTA,DESCRIZIONE,ONCLICK,HREF,FONT,AZIONE,SEQUENZA) values ('11',10,'BRAND','GESTIONE TABELLA BRAND',null,'/ANAGRAFICA/BRAND','',NULL,'15');
Insert into MENU (IDMENU,IDMENUPADRE,ETICHETTA,DESCRIZIONE,ONCLICK,HREF,FONT,AZIONE,SEQUENZA) values ('12',10,'COLORE','GESTIONE TABELLA COLORE',null,'/ANAGRAFICA/COLORE','',NULL,'20');
Insert into MENU (IDMENU,IDMENUPADRE,ETICHETTA,DESCRIZIONE,ONCLICK,HREF,FONT,AZIONE,SEQUENZA) values ('13',10,'TIPI DOCUMENTO','GESTIONE TABELLA TIPI DOCUMENTO',null,'/ANAGRAFICA/TIPIDOCUMENTO','',NULL,'25');

-- MENU GALVANICA
Insert into MENU (IDMENU,IDMENUPADRE,ETICHETTA,DESCRIZIONE,ONCLICK,HREF,FONT,AZIONE,SEQUENZA) values ('20',null,'GALVANICA','GESTIONE TABELLE GALVANICA',null,null,'fa fa-flask fa-lg',NULL,'30');
Insert into MENU (IDMENU,IDMENUPADRE,ETICHETTA,DESCRIZIONE,ONCLICK,HREF,FONT,AZIONE,SEQUENZA) values ('21',20,'IMPIANTI','GESTIONE TABELLA IMPIANTI',null,'/GALVANICA/IMPIANTI','',NULL,'35');
Insert into MENU (IDMENU,IDMENUPADRE,ETICHETTA,DESCRIZIONE,ONCLICK,HREF,FONT,AZIONE,SEQUENZA) values ('22',20,'MATERIALI','GESTIONE TABELLA MATERIALI',null,'/GALVANICA/MATERIALI','',NULL,'40');
Insert into MENU (IDMENU,IDMENUPADRE,ETICHETTA,DESCRIZIONE,ONCLICK,HREF,FONT,AZIONE,SEQUENZA) values ('23',20,'VASCHE','GESTIONE TABELLA TIPI VASCHE',null,'/GALVANICA/VASCHE','',NULL,'45');
