//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPIntranet.WS.ServicePostingRegMag {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PostingRegMag", ConfigurationName="ServicePostingRegMag.PostingRegMag_Port")]
    public interface PostingRegMag_Port {
        
        // CODEGEN: Generating message contract since the wrapper name (WSPostItemJnl_Result) of message WSPostItemJnl_Result does not match the default value (WSPostItemJnl)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PostingRegMag:WSPostItemJnl", ReplyAction="*")]
        MPIntranet.WS.ServicePostingRegMag.WSPostItemJnl_Result WSPostItemJnl(MPIntranet.WS.ServicePostingRegMag.WSPostItemJnl request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PostingRegMag:WSPostItemJnl", ReplyAction="*")]
        System.Threading.Tasks.Task<MPIntranet.WS.ServicePostingRegMag.WSPostItemJnl_Result> WSPostItemJnlAsync(MPIntranet.WS.ServicePostingRegMag.WSPostItemJnl request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WSPostItemJnl", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PostingRegMag", IsWrapped=true)]
    public partial class WSPostItemJnl {
        
        public WSPostItemJnl() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WSPostItemJnl_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PostingRegMag", IsWrapped=true)]
    public partial class WSPostItemJnl_Result {
        
        public WSPostItemJnl_Result() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PostingRegMag_PortChannel : MPIntranet.WS.ServicePostingRegMag.PostingRegMag_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PostingRegMag_PortClient : System.ServiceModel.ClientBase<MPIntranet.WS.ServicePostingRegMag.PostingRegMag_Port>, MPIntranet.WS.ServicePostingRegMag.PostingRegMag_Port {
        
        public PostingRegMag_PortClient() {
        }
        
        public PostingRegMag_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PostingRegMag_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PostingRegMag_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PostingRegMag_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MPIntranet.WS.ServicePostingRegMag.WSPostItemJnl_Result MPIntranet.WS.ServicePostingRegMag.PostingRegMag_Port.WSPostItemJnl(MPIntranet.WS.ServicePostingRegMag.WSPostItemJnl request) {
            return base.Channel.WSPostItemJnl(request);
        }
        
        public void WSPostItemJnl() {
            MPIntranet.WS.ServicePostingRegMag.WSPostItemJnl inValue = new MPIntranet.WS.ServicePostingRegMag.WSPostItemJnl();
            MPIntranet.WS.ServicePostingRegMag.WSPostItemJnl_Result retVal = ((MPIntranet.WS.ServicePostingRegMag.PostingRegMag_Port)(this)).WSPostItemJnl(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MPIntranet.WS.ServicePostingRegMag.WSPostItemJnl_Result> MPIntranet.WS.ServicePostingRegMag.PostingRegMag_Port.WSPostItemJnlAsync(MPIntranet.WS.ServicePostingRegMag.WSPostItemJnl request) {
            return base.Channel.WSPostItemJnlAsync(request);
        }
        
        public System.Threading.Tasks.Task<MPIntranet.WS.ServicePostingRegMag.WSPostItemJnl_Result> WSPostItemJnlAsync() {
            MPIntranet.WS.ServicePostingRegMag.WSPostItemJnl inValue = new MPIntranet.WS.ServicePostingRegMag.WSPostItemJnl();
            return ((MPIntranet.WS.ServicePostingRegMag.PostingRegMag_Port)(this)).WSPostItemJnlAsync(inValue);
        }
    }
}
