//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPIntranet.WS.ServiceCopiaArticolo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WS_ProductConfigurator", ConfigurationName="ServiceCopiaArticolo.WS_ProductConfigurator_Port")]
    public interface WS_ProductConfigurator_Port {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WS_ProductConfigurator:WS_CopiaArticolo", ReplyAction="*")]
        MPIntranet.WS.ServiceCopiaArticolo.WS_CopiaArticolo_Result WS_CopiaArticolo(MPIntranet.WS.ServiceCopiaArticolo.WS_CopiaArticolo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WS_ProductConfigurator:WS_CopiaArticolo", ReplyAction="*")]
        System.Threading.Tasks.Task<MPIntranet.WS.ServiceCopiaArticolo.WS_CopiaArticolo_Result> WS_CopiaArticoloAsync(MPIntranet.WS.ServiceCopiaArticolo.WS_CopiaArticolo request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WS_CopiaArticolo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WS_CopiaArticolo", Namespace="urn:microsoft-dynamics-schemas/codeunit/WS_ProductConfigurator", Order=0)]
        public MPIntranet.WS.ServiceCopiaArticolo.WS_CopiaArticoloBody Body;
        
        public WS_CopiaArticolo() {
        }
        
        public WS_CopiaArticolo(MPIntranet.WS.ServiceCopiaArticolo.WS_CopiaArticoloBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WS_ProductConfigurator")]
    public partial class WS_CopiaArticoloBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string articoloSorgente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tipoArticoloDestinazione;
        
        public WS_CopiaArticoloBody() {
        }
        
        public WS_CopiaArticoloBody(string articoloSorgente, string tipoArticoloDestinazione) {
            this.articoloSorgente = articoloSorgente;
            this.tipoArticoloDestinazione = tipoArticoloDestinazione;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WS_CopiaArticolo_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WS_CopiaArticolo_Result", Namespace="urn:microsoft-dynamics-schemas/codeunit/WS_ProductConfigurator", Order=0)]
        public MPIntranet.WS.ServiceCopiaArticolo.WS_CopiaArticolo_ResultBody Body;
        
        public WS_CopiaArticolo_Result() {
        }
        
        public WS_CopiaArticolo_Result(MPIntranet.WS.ServiceCopiaArticolo.WS_CopiaArticolo_ResultBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WS_ProductConfigurator")]
    public partial class WS_CopiaArticolo_ResultBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string articoloSorgente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tipoArticoloDestinazione;
        
        public WS_CopiaArticolo_ResultBody() {
        }
        
        public WS_CopiaArticolo_ResultBody(string articoloSorgente, string tipoArticoloDestinazione) {
            this.articoloSorgente = articoloSorgente;
            this.tipoArticoloDestinazione = tipoArticoloDestinazione;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_ProductConfigurator_PortChannel : MPIntranet.WS.ServiceCopiaArticolo.WS_ProductConfigurator_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_ProductConfigurator_PortClient : System.ServiceModel.ClientBase<MPIntranet.WS.ServiceCopiaArticolo.WS_ProductConfigurator_Port>, MPIntranet.WS.ServiceCopiaArticolo.WS_ProductConfigurator_Port {
        
        public WS_ProductConfigurator_PortClient() {
        }
        
        public WS_ProductConfigurator_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_ProductConfigurator_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_ProductConfigurator_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_ProductConfigurator_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MPIntranet.WS.ServiceCopiaArticolo.WS_CopiaArticolo_Result MPIntranet.WS.ServiceCopiaArticolo.WS_ProductConfigurator_Port.WS_CopiaArticolo(MPIntranet.WS.ServiceCopiaArticolo.WS_CopiaArticolo request) {
            return base.Channel.WS_CopiaArticolo(request);
        }
        
        public void WS_CopiaArticolo(ref string articoloSorgente, ref string tipoArticoloDestinazione) {
            MPIntranet.WS.ServiceCopiaArticolo.WS_CopiaArticolo inValue = new MPIntranet.WS.ServiceCopiaArticolo.WS_CopiaArticolo();
            inValue.Body = new MPIntranet.WS.ServiceCopiaArticolo.WS_CopiaArticoloBody();
            inValue.Body.articoloSorgente = articoloSorgente;
            inValue.Body.tipoArticoloDestinazione = tipoArticoloDestinazione;
            MPIntranet.WS.ServiceCopiaArticolo.WS_CopiaArticolo_Result retVal = ((MPIntranet.WS.ServiceCopiaArticolo.WS_ProductConfigurator_Port)(this)).WS_CopiaArticolo(inValue);
            articoloSorgente = retVal.Body.articoloSorgente;
            tipoArticoloDestinazione = retVal.Body.tipoArticoloDestinazione;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MPIntranet.WS.ServiceCopiaArticolo.WS_CopiaArticolo_Result> MPIntranet.WS.ServiceCopiaArticolo.WS_ProductConfigurator_Port.WS_CopiaArticoloAsync(MPIntranet.WS.ServiceCopiaArticolo.WS_CopiaArticolo request) {
            return base.Channel.WS_CopiaArticoloAsync(request);
        }
        
        public System.Threading.Tasks.Task<MPIntranet.WS.ServiceCopiaArticolo.WS_CopiaArticolo_Result> WS_CopiaArticoloAsync(string articoloSorgente, string tipoArticoloDestinazione) {
            MPIntranet.WS.ServiceCopiaArticolo.WS_CopiaArticolo inValue = new MPIntranet.WS.ServiceCopiaArticolo.WS_CopiaArticolo();
            inValue.Body = new MPIntranet.WS.ServiceCopiaArticolo.WS_CopiaArticoloBody();
            inValue.Body.articoloSorgente = articoloSorgente;
            inValue.Body.tipoArticoloDestinazione = tipoArticoloDestinazione;
            return ((MPIntranet.WS.ServiceCopiaArticolo.WS_ProductConfigurator_Port)(this)).WS_CopiaArticoloAsync(inValue);
        }
    }
}
