//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPIntranet.WS.MTPWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WS_ProductConfigurator", ConfigurationName="MTPWS.WS_ProductConfigurator_Port")]
    public interface WS_ProductConfigurator_Port {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WS_ProductConfigurator:Create_FirmPlanned" +
            "ProdOrder", ReplyAction="*")]
        MPIntranet.WS.MTPWS.Create_FirmPlannedProdOrder_Result Create_FirmPlannedProdOrder(MPIntranet.WS.MTPWS.Create_FirmPlannedProdOrder request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WS_ProductConfigurator:Create_FirmPlanned" +
            "ProdOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<MPIntranet.WS.MTPWS.Create_FirmPlannedProdOrder_Result> Create_FirmPlannedProdOrderAsync(MPIntranet.WS.MTPWS.Create_FirmPlannedProdOrder request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WS_ProductConfigurator:WS_CopiaArticolo", ReplyAction="*")]
        MPIntranet.WS.MTPWS.WS_CopiaArticolo_Result WS_CopiaArticolo(MPIntranet.WS.MTPWS.WS_CopiaArticolo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WS_ProductConfigurator:WS_CopiaArticolo", ReplyAction="*")]
        System.Threading.Tasks.Task<MPIntranet.WS.MTPWS.WS_CopiaArticolo_Result> WS_CopiaArticoloAsync(MPIntranet.WS.MTPWS.WS_CopiaArticolo request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Create_FirmPlannedProdOrder {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Create_FirmPlannedProdOrder", Namespace="urn:microsoft-dynamics-schemas/codeunit/WS_ProductConfigurator", Order=0)]
        public MPIntranet.WS.MTPWS.Create_FirmPlannedProdOrderBody Body;
        
        public Create_FirmPlannedProdOrder() {
        }
        
        public Create_FirmPlannedProdOrder(MPIntranet.WS.MTPWS.Create_FirmPlannedProdOrderBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WS_ProductConfigurator")]
    public partial class Create_FirmPlannedProdOrderBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string itemNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal qty;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string dueDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string locationCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string prodOrderNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string description2;
        
        public Create_FirmPlannedProdOrderBody() {
        }
        
        public Create_FirmPlannedProdOrderBody(string itemNo, decimal qty, string dueDate, string locationCode, string prodOrderNo, string description, string description2) {
            this.itemNo = itemNo;
            this.qty = qty;
            this.dueDate = dueDate;
            this.locationCode = locationCode;
            this.prodOrderNo = prodOrderNo;
            this.description = description;
            this.description2 = description2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Create_FirmPlannedProdOrder_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Create_FirmPlannedProdOrder_Result", Namespace="urn:microsoft-dynamics-schemas/codeunit/WS_ProductConfigurator", Order=0)]
        public MPIntranet.WS.MTPWS.Create_FirmPlannedProdOrder_ResultBody Body;
        
        public Create_FirmPlannedProdOrder_Result() {
        }
        
        public Create_FirmPlannedProdOrder_Result(MPIntranet.WS.MTPWS.Create_FirmPlannedProdOrder_ResultBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WS_ProductConfigurator")]
    public partial class Create_FirmPlannedProdOrder_ResultBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string prodOrderNo;
        
        public Create_FirmPlannedProdOrder_ResultBody() {
        }
        
        public Create_FirmPlannedProdOrder_ResultBody(string prodOrderNo) {
            this.prodOrderNo = prodOrderNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WS_CopiaArticolo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WS_CopiaArticolo", Namespace="urn:microsoft-dynamics-schemas/codeunit/WS_ProductConfigurator", Order=0)]
        public MPIntranet.WS.MTPWS.WS_CopiaArticoloBody Body;
        
        public WS_CopiaArticolo() {
        }
        
        public WS_CopiaArticolo(MPIntranet.WS.MTPWS.WS_CopiaArticoloBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WS_ProductConfigurator")]
    public partial class WS_CopiaArticoloBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string articoloSorgente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tipoArticoloDestinazione;
        
        public WS_CopiaArticoloBody() {
        }
        
        public WS_CopiaArticoloBody(string articoloSorgente, string tipoArticoloDestinazione) {
            this.articoloSorgente = articoloSorgente;
            this.tipoArticoloDestinazione = tipoArticoloDestinazione;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WS_CopiaArticolo_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WS_CopiaArticolo_Result", Namespace="urn:microsoft-dynamics-schemas/codeunit/WS_ProductConfigurator", Order=0)]
        public MPIntranet.WS.MTPWS.WS_CopiaArticolo_ResultBody Body;
        
        public WS_CopiaArticolo_Result() {
        }
        
        public WS_CopiaArticolo_Result(MPIntranet.WS.MTPWS.WS_CopiaArticolo_ResultBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WS_ProductConfigurator")]
    public partial class WS_CopiaArticolo_ResultBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string articoloSorgente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tipoArticoloDestinazione;
        
        public WS_CopiaArticolo_ResultBody() {
        }
        
        public WS_CopiaArticolo_ResultBody(string articoloSorgente, string tipoArticoloDestinazione) {
            this.articoloSorgente = articoloSorgente;
            this.tipoArticoloDestinazione = tipoArticoloDestinazione;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_ProductConfigurator_PortChannel : MPIntranet.WS.MTPWS.WS_ProductConfigurator_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_ProductConfigurator_PortClient : System.ServiceModel.ClientBase<MPIntranet.WS.MTPWS.WS_ProductConfigurator_Port>, MPIntranet.WS.MTPWS.WS_ProductConfigurator_Port {
        
        public WS_ProductConfigurator_PortClient() {
        }
        
        public WS_ProductConfigurator_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_ProductConfigurator_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_ProductConfigurator_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_ProductConfigurator_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MPIntranet.WS.MTPWS.Create_FirmPlannedProdOrder_Result MPIntranet.WS.MTPWS.WS_ProductConfigurator_Port.Create_FirmPlannedProdOrder(MPIntranet.WS.MTPWS.Create_FirmPlannedProdOrder request) {
            return base.Channel.Create_FirmPlannedProdOrder(request);
        }
        
        public void Create_FirmPlannedProdOrder(string itemNo, decimal qty, string dueDate, string locationCode, ref string prodOrderNo, string description, string description2) {
            MPIntranet.WS.MTPWS.Create_FirmPlannedProdOrder inValue = new MPIntranet.WS.MTPWS.Create_FirmPlannedProdOrder();
            inValue.Body = new MPIntranet.WS.MTPWS.Create_FirmPlannedProdOrderBody();
            inValue.Body.itemNo = itemNo;
            inValue.Body.qty = qty;
            inValue.Body.dueDate = dueDate;
            inValue.Body.locationCode = locationCode;
            inValue.Body.prodOrderNo = prodOrderNo;
            inValue.Body.description = description;
            inValue.Body.description2 = description2;
            MPIntranet.WS.MTPWS.Create_FirmPlannedProdOrder_Result retVal = ((MPIntranet.WS.MTPWS.WS_ProductConfigurator_Port)(this)).Create_FirmPlannedProdOrder(inValue);
            prodOrderNo = retVal.Body.prodOrderNo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MPIntranet.WS.MTPWS.Create_FirmPlannedProdOrder_Result> MPIntranet.WS.MTPWS.WS_ProductConfigurator_Port.Create_FirmPlannedProdOrderAsync(MPIntranet.WS.MTPWS.Create_FirmPlannedProdOrder request) {
            return base.Channel.Create_FirmPlannedProdOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<MPIntranet.WS.MTPWS.Create_FirmPlannedProdOrder_Result> Create_FirmPlannedProdOrderAsync(string itemNo, decimal qty, string dueDate, string locationCode, string prodOrderNo, string description, string description2) {
            MPIntranet.WS.MTPWS.Create_FirmPlannedProdOrder inValue = new MPIntranet.WS.MTPWS.Create_FirmPlannedProdOrder();
            inValue.Body = new MPIntranet.WS.MTPWS.Create_FirmPlannedProdOrderBody();
            inValue.Body.itemNo = itemNo;
            inValue.Body.qty = qty;
            inValue.Body.dueDate = dueDate;
            inValue.Body.locationCode = locationCode;
            inValue.Body.prodOrderNo = prodOrderNo;
            inValue.Body.description = description;
            inValue.Body.description2 = description2;
            return ((MPIntranet.WS.MTPWS.WS_ProductConfigurator_Port)(this)).Create_FirmPlannedProdOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MPIntranet.WS.MTPWS.WS_CopiaArticolo_Result MPIntranet.WS.MTPWS.WS_ProductConfigurator_Port.WS_CopiaArticolo(MPIntranet.WS.MTPWS.WS_CopiaArticolo request) {
            return base.Channel.WS_CopiaArticolo(request);
        }
        
        public void WS_CopiaArticolo(ref string articoloSorgente, ref string tipoArticoloDestinazione) {
            MPIntranet.WS.MTPWS.WS_CopiaArticolo inValue = new MPIntranet.WS.MTPWS.WS_CopiaArticolo();
            inValue.Body = new MPIntranet.WS.MTPWS.WS_CopiaArticoloBody();
            inValue.Body.articoloSorgente = articoloSorgente;
            inValue.Body.tipoArticoloDestinazione = tipoArticoloDestinazione;
            MPIntranet.WS.MTPWS.WS_CopiaArticolo_Result retVal = ((MPIntranet.WS.MTPWS.WS_ProductConfigurator_Port)(this)).WS_CopiaArticolo(inValue);
            articoloSorgente = retVal.Body.articoloSorgente;
            tipoArticoloDestinazione = retVal.Body.tipoArticoloDestinazione;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MPIntranet.WS.MTPWS.WS_CopiaArticolo_Result> MPIntranet.WS.MTPWS.WS_ProductConfigurator_Port.WS_CopiaArticoloAsync(MPIntranet.WS.MTPWS.WS_CopiaArticolo request) {
            return base.Channel.WS_CopiaArticoloAsync(request);
        }
        
        public System.Threading.Tasks.Task<MPIntranet.WS.MTPWS.WS_CopiaArticolo_Result> WS_CopiaArticoloAsync(string articoloSorgente, string tipoArticoloDestinazione) {
            MPIntranet.WS.MTPWS.WS_CopiaArticolo inValue = new MPIntranet.WS.MTPWS.WS_CopiaArticolo();
            inValue.Body = new MPIntranet.WS.MTPWS.WS_CopiaArticoloBody();
            inValue.Body.articoloSorgente = articoloSorgente;
            inValue.Body.tipoArticoloDestinazione = tipoArticoloDestinazione;
            return ((MPIntranet.WS.MTPWS.WS_ProductConfigurator_Port)(this)).WS_CopiaArticoloAsync(inValue);
        }
    }
}
