use mpi
go

CREATE TABLE [SPCONTROLLI]
(
 [IDSPCONTROLLO]     int IDENTITY (1, 1) NOT NULL ,
 [CODICE]			nvarchar(12) NOT NULL ,
 [DESCRIZIONE]		nvarchar(50) NOT NULL ,
 [TIPO]				nvarchar(12) NOT NULL ,
 [MINIMO]			FLOAT NULL ,
 [MASSIMO]			FLOAT NULL ,
 [DEFAULT]			FLOAT NULL ,
 [CANCELLATO]     bit NOT NULL ,
 [DATAMODIFICA]   datetime NOT NULL ,
 [UTENTEMODIFICA] nvarchar(50) NOT NULL ,
 CONSTRAINT [PK_SPCONTROLLO] PRIMARY KEY CLUSTERED ([IDSPCONTROLLO] ASC)
);
GO

CREATE TABLE [SPCONTROLLI_LOG]
(
 [IDSPCONTROLLO]     int NULL ,
 [CODICE]			nvarchar(12) NULL ,
 [DESCRIZIONE]		nvarchar(50) NULL ,
 [TIPO]				nvarchar(12) NULL ,
 [MINIMO]			FLOAT NULL ,
 [MASSIMO]			FLOAT NULL ,
 [DEFAULT]			FLOAT NULL ,
 [CANCELLATO]     bit  NULL ,
 [DATAMODIFICA]   datetime NULL ,
 [UTENTEMODIFICA] nvarchar(50) NULL ,
);
GO
CREATE OR ALTER TRIGGER SPCONTROLLI_LOG_I
ON SPCONTROLLI
AFTER INSERT
AS
BEGIN 
INSERT INTO SPCONTROLLI_LOG ([IDSPCONTROLLO], [CODICE],[DESCRIZIONE],[TIPO],[MINIMO],[MASSIMO],[DEFAULT],CANCELLATO, DATAMODIFICA, UTENTEMODIFICA) 
SELECT I.[IDSPCONTROLLO], I.[CODICE],I.[DESCRIZIONE],I.[TIPO],I.[MINIMO],I.[MASSIMO],I.[DEFAULT],I.CANCELLATO, I.DATAMODIFICA, I.UTENTEMODIFICA FROM INSERTED I
END

GO
CREATE OR ALTER TRIGGER SPCONTROLLI_LOG_U
ON SPCONTROLLI
AFTER UPDATE
AS
BEGIN 
INSERT INTO SPCONTROLLI_LOG ([IDSPCONTROLLO], [CODICE],[DESCRIZIONE],[TIPO],[MINIMO],[MASSIMO],[DEFAULT],CANCELLATO, DATAMODIFICA, UTENTEMODIFICA) 
SELECT I.[IDSPCONTROLLO], I.[CODICE],I.[DESCRIZIONE],I.[TIPO],I.[MINIMO],I.[MASSIMO],I.[DEFAULT],I.CANCELLATO, I.DATAMODIFICA, I.UTENTEMODIFICA FROM INSERTED I
INNER JOIN DELETED D ON D.[IDSPCONTROLLO]=I.[IDSPCONTROLLO]
END
GO


CREATE TABLE [SPMASTERS]
(
 [IDSPMASTER]         int IDENTITY (1, 1) NOT NULL ,
 [AREAPRODUZIONE]     nvarchar(20) NOT NULL ,
 [TASK]				nvarchar(10) NOT NULL ,
 [CODICE]			nvarchar(12) NOT NULL ,
 [DESCRIZIONE]		nvarchar(50) NOT NULL ,
 [CANCELLATO]     bit NOT NULL ,
 [DATAMODIFICA]   datetime NOT NULL ,
 [UTENTEMODIFICA] nvarchar(50) NOT NULL ,
 CONSTRAINT [PK_SPMASTER] PRIMARY KEY CLUSTERED ([IDSPMASTER] ASC)
);
GO
CREATE INDEX IDX_SPMASTER_1 ON SPMASTERS(AREAPRODUZIONE)
GO

CREATE TABLE [SPMASTERS_LOG]
(
 [IDSPMASTER]         int NULL ,
 [AREAPRODUZIONE]     nvarchar(20)  NULL ,
 [TASK]				nvarchar(10)  NULL ,
 [CODICE]			nvarchar(12)  NULL ,
 [DESCRIZIONE]		nvarchar(50)  NULL ,
 [CANCELLATO]     bit  NULL ,
 [DATAMODIFICA]   datetime  NULL ,
 [UTENTEMODIFICA] nvarchar(50)  NULL 
);
GO

CREATE OR ALTER TRIGGER SPMASTERS_LOG_I
ON SPMASTERS
AFTER INSERT
AS
BEGIN 
INSERT INTO SPMASTERS_LOG ([IDSPMASTER], [AREAPRODUZIONE],[TASK],[CODICE],DESCRIZIONE,CANCELLATO, DATAMODIFICA, UTENTEMODIFICA) 
SELECT I.[IDSPMASTER], I.[AREAPRODUZIONE],I.[TASK],I.[CODICE],I.DESCRIZIONE,I.CANCELLATO, I.DATAMODIFICA, I.UTENTEMODIFICA FROM INSERTED I
END


GO
CREATE OR ALTER TRIGGER SPMASTERS_LOG_U
ON SPMASTERS
AFTER UPDATE
AS
BEGIN 
INSERT INTO SPMASTERS_LOG ([IDSPMASTER], [AREAPRODUZIONE],[TASK],[CODICE],DESCRIZIONE,CANCELLATO, DATAMODIFICA, UTENTEMODIFICA) 
SELECT I.[IDSPMASTER], I.[AREAPRODUZIONE],I.[TASK],I.[CODICE],I.DESCRIZIONE,I.CANCELLATO, I.DATAMODIFICA, I.UTENTEMODIFICA FROM INSERTED I
INNER JOIN DELETED D ON D.[IDSPMASTER]=I.[IDSPMASTER]
END
GO

CREATE TABLE [SPELEMENTI]
(
 [IDSPELEMENTO]		int IDENTITY (1, 1) NOT NULL ,
 [IDSPMASTER]     int NOT NULL ,
 [IDSPCONTROLLO]     int  NULL ,
 [SEQUENZA]       int NOT NULL ,
 [OBBLIGATORIO]    BIT NULL ,
 [TIPOELEMENTO]  NVARCHAR(12) NOT NULL,
 [TESTO]		NVARCHAR(25) NULL,
 [CANCELLATO]     bit NOT NULL ,
 [DATAMODIFICA]   datetime NOT NULL ,
 [UTENTEMODIFICA] nvarchar(50) NOT NULL ,
 CONSTRAINT [PK_SPELEMENTI] PRIMARY KEY CLUSTERED ([IDSPELEMENTO] ASC),
 CONSTRAINT [FK_SPELEMENTI_1] FOREIGN KEY ([IDSPMASTER])  REFERENCES [SPMASTERS]([IDSPMASTER]),
 CONSTRAINT [FK_SPELEMENTI_2] FOREIGN KEY ([IDSPCONTROLLO])  REFERENCES [SPCONTROLLI]([IDSPCONTROLLO])
);



CREATE TABLE [SPELEMENTI_LOG]
(
 [IDSPELEMENTO]		int NULL ,
 [IDSPMASTER]     int  NULL ,
 [IDSPCONTROLLO]     int  NULL ,
 [SEQUENZA]       int  NULL ,
 [OBBLIGATORIO]    BIT NULL ,
 [TIPOELEMENTO]  NVARCHAR(12)  NULL,
 [TESTO]		NVARCHAR(25) NULL,
 [CANCELLATO]     bit  NULL ,
 [DATAMODIFICA]   datetime  NULL ,
 [UTENTEMODIFICA] nvarchar(50)  NULL 
);
GO

CREATE OR ALTER TRIGGER SPELEMENTI_LOG_I
ON SPELEMENTI
AFTER INSERT
AS
BEGIN 
INSERT INTO SPELEMENTI_LOG ([IDSPELEMENTO], [IDSPMASTER],[IDSPCONTROLLO],[SEQUENZA],[OBBLIGATORIO],[TIPOELEMENTO],[TESTO],CANCELLATO, DATAMODIFICA, UTENTEMODIFICA) 
SELECT I.[IDSPELEMENTO], I.[IDSPMASTER],I.[IDSPCONTROLLO],I.[SEQUENZA],I.[OBBLIGATORIO],I.[TIPOELEMENTO],I.[TESTO],I.CANCELLATO, I.DATAMODIFICA, I.UTENTEMODIFICA FROM INSERTED I
END


GO
CREATE OR ALTER TRIGGER SPELEMENTI_LOG_U
ON SPELEMENTI
AFTER UPDATE
AS
BEGIN 
INSERT INTO SPELEMENTI_LOG ([IDSPELEMENTO], [IDSPMASTER],[IDSPCONTROLLO],[SEQUENZA],[OBBLIGATORIO],[TIPOELEMENTO],[TESTO],CANCELLATO, DATAMODIFICA, UTENTEMODIFICA) 
SELECT I.[IDSPELEMENTO], I.[IDSPMASTER],I.[IDSPCONTROLLO],I.[SEQUENZA],I.[OBBLIGATORIO],I.[TIPOELEMENTO],I.[TESTO],I.CANCELLATO, I.DATAMODIFICA, I.UTENTEMODIFICA FROM INSERTED I
INNER JOIN DELETED D ON D.[IDSPMASTER]=I.[IDSPMASTER]
END

GO

CREATE TABLE [SPELEMENTILISTA]
(
 [IDSPELEMENTOLISTA]		int IDENTITY (1, 1) NOT NULL ,
 [IDSPCONTROLLO]     int NOT NULL ,
 [CODICE]			nvarchar(12) NOT NULL ,
 [DESCRIZIONE]		nvarchar(50) NOT NULL ,
 [SEQUENZA]       int NOT NULL ,
 [DEFAULT]			BIT NULL ,
 [CANCELLATO]     bit NOT NULL ,
 [DATAMODIFICA]   datetime NOT NULL ,
 [UTENTEMODIFICA] nvarchar(50) NOT NULL ,
 CONSTRAINT [PK_SPELEMENTILISTA] PRIMARY KEY CLUSTERED ([IDSPELEMENTOLISTA] ASC),
 CONSTRAINT [FK_SPELEMENTILISTA_1] FOREIGN KEY ([IDSPCONTROLLO])  REFERENCES [SPCONTROLLI]([IDSPCONTROLLO])
);
GO
CREATE INDEX IDX_SPELEMENTILISTA_1 ON SPELEMENTILISTA(IDSPCONTROLLO)
GO
CREATE TABLE [SPELEMENTILISTA_LOG]
(
 [IDSPELEMENTOLISTA]		int NULL ,
 [IDSPCONTROLLO]     int  NULL ,
 [CODICE]			nvarchar(12) NULL ,
 [DESCRIZIONE]		nvarchar(50) NULL ,
 [SEQUENZA]       int  NULL ,
 [DEFAULT]    BIT NULL ,
 [CANCELLATO]     bit  NULL ,
 [DATAMODIFICA]   datetime  NULL ,
 [UTENTEMODIFICA] nvarchar(50)  NULL 
);
GO

CREATE OR ALTER TRIGGER SPELEMENTILISTA_LOG_I
ON SPELEMENTILISTA
AFTER INSERT
AS
BEGIN 
INSERT INTO SPELEMENTILISTA_LOG([IDSPELEMENTOLISTA], [IDSPCONTROLLO],[CODICE],[DESCRIZIONE],[SEQUENZA],[DEFAULT],CANCELLATO, DATAMODIFICA, UTENTEMODIFICA) 
SELECT I.[IDSPELEMENTOLISTA], I.[IDSPCONTROLLO],I.[CODICE],I.[DESCRIZIONE],I.[SEQUENZA],I.[DEFAULT],I.CANCELLATO, I.DATAMODIFICA, I.UTENTEMODIFICA FROM INSERTED I
END


GO
CREATE OR ALTER TRIGGER SPELEMENTILISTA_LOG_U
ON SPELEMENTILISTA
AFTER UPDATE
AS
BEGIN 
INSERT INTO SPELEMENTILISTA_LOG([IDSPELEMENTOLISTA], [IDSPCONTROLLO],[CODICE],[DESCRIZIONE],[SEQUENZA],[DEFAULT],CANCELLATO, DATAMODIFICA, UTENTEMODIFICA) 
SELECT I.[IDSPELEMENTOLISTA], I.[IDSPCONTROLLO],I.[CODICE],I.[DESCRIZIONE],I.[SEQUENZA],I.[DEFAULT],I.CANCELLATO, I.DATAMODIFICA, I.UTENTEMODIFICA FROM INSERTED I
INNER JOIN DELETED D ON D.[IDSPELEMENTOLISTA]=I.[IDSPELEMENTOLISTA]

END

GO

CREATE TABLE [SPSCHEDE]
(
 [IDSPSCHEDA]		int IDENTITY (1, 1) NOT NULL ,
 [IDSPMASTER]     int NOT NULL ,
 [CODICE]			nvarchar(12) NOT NULL ,
 [DESCRIZIONE]		nvarchar(50) NOT NULL ,
 [ANAGRAFICA]		nvarchar(25) NOT NULL ,
 [IDBRAND]		int NOT NULL ,
 [AREAPRODUZIONE]     nvarchar(20) NOT NULL ,
 [TASK]				nvarchar(10) NOT NULL ,
 [FOTO]       NVARCHAR(20) NULL ,
 [CANCELLATO]     bit NOT NULL ,
 [DATAMODIFICA]   datetime NOT NULL ,
 [UTENTEMODIFICA] nvarchar(50) NOT NULL ,
 CONSTRAINT [PK_SPSCHEDE] PRIMARY KEY CLUSTERED ([IDSPSCHEDA] ASC),
 CONSTRAINT [FK_SPSCHEDE_1] FOREIGN KEY ([IDSPMASTER])  REFERENCES [SPMASTERS]([IDSPMASTER])
);
GO
CREATE INDEX IDX_SPSCHEDA_1 ON SPSCHEDE(AREAPRODUZIONE)
GO
CREATE TABLE [SPSCHEDE_LOG]
(
 [IDSPSCHEDA]		int NULL ,
 [IDSPMASTER]     int  NULL ,
 [CODICE]			nvarchar(12)  NULL ,
 [DESCRIZIONE]		nvarchar(50)  NULL ,
 [ANAGRAFICA]		nvarchar(25)  NULL ,
 [IDBRAND]		int  NULL ,
 [AREAPRODUZIONE]     nvarchar(20)  NULL ,
 [TASK]				nvarchar(10)  NULL ,
 [FOTO]       NVARCHAR(20) NULL ,
 [CANCELLATO]     bit  NULL ,
 [DATAMODIFICA]   datetime  NULL ,
 [UTENTEMODIFICA] nvarchar(50)  NULL 
);
GO

CREATE OR ALTER TRIGGER SPSCHEDE_LOG_I
ON SPSCHEDE
AFTER INSERT
AS
BEGIN 
INSERT INTO SPSCHEDE_LOG([IDSPSCHEDA], [IDSPMASTER],[CODICE],[DESCRIZIONE],[ANAGRAFICA],[IDBRAND],[AREAPRODUZIONE],[TASK],[FOTO],CANCELLATO, DATAMODIFICA, UTENTEMODIFICA) 
SELECT I.[IDSPSCHEDA], I.[IDSPMASTER],I.[CODICE],I.[DESCRIZIONE],I.[ANAGRAFICA],I.[IDBRAND],I.[AREAPRODUZIONE],I.[TASK],I.[FOTO],I.CANCELLATO, I.DATAMODIFICA, I.UTENTEMODIFICA FROM INSERTED I
END


GO
CREATE OR ALTER TRIGGER SPSCHEDE_LOG_U
ON SPSCHEDE
AFTER UPDATE
AS
BEGIN 
INSERT INTO SPSCHEDE_LOG([IDSPSCHEDA], [IDSPMASTER],[CODICE],[DESCRIZIONE],[ANAGRAFICA],[IDBRAND],[AREAPRODUZIONE],[TASK],[FOTO],CANCELLATO, DATAMODIFICA, UTENTEMODIFICA) 
SELECT I.[IDSPSCHEDA], I.[IDSPMASTER],I.[CODICE],I.[DESCRIZIONE],I.[ANAGRAFICA],I.[IDBRAND],I.[AREAPRODUZIONE],I.[TASK],I.[FOTO],I.CANCELLATO, I.DATAMODIFICA, I.UTENTEMODIFICA FROM INSERTED I
INNER JOIN DELETED D ON D.[IDSPSCHEDA]=I.[IDSPSCHEDA]

END

GO

CREATE TABLE [SPVALORISCHEDE]
(
 [IDSPVALORESCHEDA]		int IDENTITY (1, 1) NOT NULL ,
 [IDSPSCHEDA]     int NOT NULL ,
 [IDSPELEMENTO] INT NOT NULL,
 [CODICE]			nvarchar(12) NULL ,
 [DESCRIZIONE]		nvarchar(50) NULL ,
 [TIPO]				nvarchar(12) NULL ,
 [VALOREN]	FLOAT NULL ,
 [VALORET] NVARCHAR(30) NULL,
 [VALORED] DATETIME NULL,
 [CANCELLATO]     bit NOT NULL ,
 [DATAMODIFICA]   datetime NOT NULL ,
 [UTENTEMODIFICA] nvarchar(50) NOT NULL ,
 CONSTRAINT [PK_SPVALORESCHEDA] PRIMARY KEY CLUSTERED ([IDSPVALORESCHEDA] ASC),
 CONSTRAINT [FK_SPVALORESCHEDA_1] FOREIGN KEY ([IDSPSCHEDA])  REFERENCES [SPSCHEDE]([IDSPSCHEDA]),
 CONSTRAINT [FK_SPVALORESCHEDA_2] FOREIGN KEY ([IDSPELEMENTO])  REFERENCES [SPELEMENTI]([IDSPELEMENTO])
);
GO
CREATE INDEX IDX_SPVALORESCHEDA_1 ON SPVALORISCHEDE(IDSPSCHEDA)
GO 

CREATE TABLE [SPVALORISCHEDE_LOG]
(
 [IDSPVALORESCHEDA]		int NULL ,
 [IDSPSCHEDA]     int  NULL ,
 [IDSPELEMENTO] INT  NULL,
 [CODICE]			nvarchar(12) NULL ,
 [DESCRIZIONE]		nvarchar(50) NULL ,
 [TIPO]				nvarchar(12) NULL ,
 [VALOREN]	FLOAT NULL ,
 [VALORET] NVARCHAR(30) NULL,
 [VALORED] DATETIME NULL,
 [CANCELLATO]     bit NOT NULL ,
 [DATAMODIFICA]   datetime  NULL ,
 [UTENTEMODIFICA] nvarchar(50)  NULL 
);

GO 


CREATE OR ALTER TRIGGER SPVALORISCHEDE_LOG_1
ON SPVALORISCHEDE
AFTER INSERT
AS
BEGIN 
INSERT INTO SPVALORISCHEDE_LOG([IDSPVALORESCHEDA],[IDSPSCHEDA], [IDSPELEMENTO],[CODICE],[DESCRIZIONE],[TIPO],[VALOREN],[VALORET],[VALORED],CANCELLATO, DATAMODIFICA, UTENTEMODIFICA) 
SELECT I.[IDSPVALORESCHEDA],I.[IDSPSCHEDA], I.[IDSPELEMENTO],I.[CODICE],I.[DESCRIZIONE],I.[TIPO],I.[VALOREN],I.[VALORET],I.[VALORED],I.CANCELLATO, I.DATAMODIFICA, I.UTENTEMODIFICA FROM INSERTED I
END


GO
CREATE OR ALTER TRIGGER SPVALORISCHEDE_LOG_U
ON SPVALORISCHEDE
AFTER UPDATE
AS
BEGIN 
INSERT INTO SPVALORISCHEDE_LOG([IDSPVALORESCHEDA],[IDSPSCHEDA], [IDSPELEMENTO],[CODICE],[DESCRIZIONE],[TIPO],[VALOREN],[VALORET],[VALORED],CANCELLATO, DATAMODIFICA, UTENTEMODIFICA) 
SELECT I.[IDSPVALORESCHEDA],I.[IDSPSCHEDA], I.[IDSPELEMENTO],I.[CODICE],I.[DESCRIZIONE],I.[TIPO],I.[VALOREN],I.[VALORET],I.[VALORED],I.CANCELLATO, I.DATAMODIFICA, I.UTENTEMODIFICA FROM INSERTED I
INNER JOIN DELETED D ON D.[IDSPVALORESCHEDA]=I.[IDSPVALORESCHEDA]

END
