
USE [MPI]
GO

ALTER TABLE [dbo].[ARTICOLI] DROP CONSTRAINT [FK__ARTICOLI__IDBRAN__5812160E]
GO
ALTER TABLE [dbo].SPSCHEDE DROP CONSTRAINT [FK_SPSCHEDE_2]
GO DROP TABLE BRANDS
GO
DROP TABLE BRANDS_LOG


USE [MPI_TEST]
GO

ALTER TABLE [dbo].[ARTICOLI] DROP CONSTRAINT [FK__ARTICOLI__IDBRAN__5812160E]
GO
ALTER TABLE [dbo].SPSCHEDE DROP CONSTRAINT [FK_SPSCHEDE_2]
GO
DROP TABLE BRANDS
GO
DROP TABLE BRANDS_LOG

