use mpi_test

alter table COMPONENTI ALTER COLUMN DESCRIZIONE NVARCHAR(100) NULL
alter table COMPONENTI_LOG ALTER COLUMN DESCRIZIONE NVARCHAR(100) NULL

alter table DIBA ALTER COLUMN DESCRIZIONE NVARCHAR(100) NULL
alter table DIBA_LOG ALTER COLUMN DESCRIZIONE NVARCHAR(100) NULL

alter table FASICICLO ALTER COLUMN DESCRIZIONE NVARCHAR(100) NULL
alter table FASICICLO_LOG ALTER COLUMN DESCRIZIONE NVARCHAR(100) NULL

USE MPI


alter table COMPONENTI ALTER COLUMN DESCRIZIONE NVARCHAR(100) NULL
alter table COMPONENTI_LOG ALTER COLUMN DESCRIZIONE NVARCHAR(100) NULL

alter table DIBA ALTER COLUMN DESCRIZIONE NVARCHAR(100) NULL
alter table DIBA_LOG ALTER COLUMN DESCRIZIONE NVARCHAR(100) NULL

alter table FASICICLO ALTER COLUMN DESCRIZIONE NVARCHAR(100) NULL
alter table FASICICLO_LOG ALTER COLUMN DESCRIZIONE NVARCHAR(100) NULL