use mpi_test

alter table SPSCHEDE ADD VERSIONE INTEGER NULL
alter table SPSCHEDE_log ADD VERSIONE INTEGER NULL
alter table SPSCHEDE ADD STATO NVARCHAR(20) NULL
alter table SPSCHEDE_log ADD STATO NVARCHAR(20)NULL

CREATE INDEX IDX_SPSCHEDE_2 ON SPSCHEDE(CODICE)

UPDATE SPSCHEDE SET VERSIONE = 1
ALTER TABLE SPSCHEDE ALTER COLUMN VERSIONE INTEGER NOT NULL

CREATE OR ALTER TRIGGER SPSCHEDE_LOG_I
ON SPSCHEDE
AFTER INSERT
AS
BEGIN 
INSERT INTO SPSCHEDE_LOG([IDSPSCHEDA], [IDSPMASTER],[CODICE],[DESCRIZIONE],[ANAGRAFICA],[AREAPRODUZIONE],[TASK],[FOTO],CANCELLATO, DATAMODIFICA, UTENTEMODIFICA,VERSIONE,STATO) 
SELECT I.[IDSPSCHEDA], I.[IDSPMASTER],I.[CODICE],I.[DESCRIZIONE],I.[ANAGRAFICA],I.[AREAPRODUZIONE],I.[TASK],I.[FOTO],I.CANCELLATO, I.DATAMODIFICA, I.UTENTEMODIFICA,I.VERSIONE,I.STATO FROM INSERTED I
END

UPDATE SPSCHEDE SET VERSIONE = 1
ALTER TABLE SPSCHEDE ALTER COLUMN VERSIONE INTEGER NOT NULL

UPDATE SPSCHEDE SET STATO = 'ATTIVA'

GO
CREATE OR ALTER TRIGGER SPSCHEDE_LOG_U
ON SPSCHEDE
AFTER UPDATE
AS
BEGIN 
INSERT INTO SPSCHEDE_LOG([IDSPSCHEDA], [IDSPMASTER],[CODICE],[DESCRIZIONE],[ANAGRAFICA],[AREAPRODUZIONE],[TASK],[FOTO],CANCELLATO, DATAMODIFICA, UTENTEMODIFICA,VERSIONE,STATO) 
SELECT I.[IDSPSCHEDA], I.[IDSPMASTER],I.[CODICE],I.[DESCRIZIONE],I.[ANAGRAFICA],I.[AREAPRODUZIONE],I.[TASK],I.[FOTO],I.CANCELLATO, I.DATAMODIFICA, I.UTENTEMODIFICA,I.VERSIONE,I.STATO FROM INSERTED I
INNER JOIN DELETED D ON D.[IDSPSCHEDA]=I.[IDSPSCHEDA]

END

GO

USE MPI

GO

alter table SPSCHEDE ADD VERSIONE INTEGER NULL
alter table SPSCHEDE_log ADD VERSIONE INTEGER NULL
alter table SPSCHEDE ADD STATO NVARCHAR(20) NULL
alter table SPSCHEDE_log ADD STATO NVARCHAR(20)NULL

CREATE INDEX IDX_SPSCHEDE_2 ON SPSCHEDE(CODICE)


UPDATE SPSCHEDE SET VERSIONE = 1
ALTER TABLE SPSCHEDE ALTER COLUMN VERSIONE INTEGER NOT NULL

UPDATE SPSCHEDE SET STATO = 'ATTIVA'


CREATE OR ALTER TRIGGER SPSCHEDE_LOG_I
ON SPSCHEDE
AFTER INSERT
AS
BEGIN 
INSERT INTO SPSCHEDE_LOG([IDSPSCHEDA], [IDSPMASTER],[CODICE],[DESCRIZIONE],[ANAGRAFICA],[AREAPRODUZIONE],[TASK],[FOTO],CANCELLATO, DATAMODIFICA, UTENTEMODIFICA,VERSIONE,STATO) 
SELECT I.[IDSPSCHEDA], I.[IDSPMASTER],I.[CODICE],I.[DESCRIZIONE],I.[ANAGRAFICA],I.[AREAPRODUZIONE],I.[TASK],I.[FOTO],I.CANCELLATO, I.DATAMODIFICA, I.UTENTEMODIFICA,I.VERSIONE,I.STATO FROM INSERTED I
END


GO
CREATE OR ALTER TRIGGER SPSCHEDE_LOG_U
ON SPSCHEDE
AFTER UPDATE
AS
BEGIN 
INSERT INTO SPSCHEDE_LOG([IDSPSCHEDA], [IDSPMASTER],[CODICE],[DESCRIZIONE],[ANAGRAFICA],[AREAPRODUZIONE],[TASK],[FOTO],CANCELLATO, DATAMODIFICA, UTENTEMODIFICA,VERSIONE,STATO) 
SELECT I.[IDSPSCHEDA], I.[IDSPMASTER],I.[CODICE],I.[DESCRIZIONE],I.[ANAGRAFICA],I.[AREAPRODUZIONE],I.[TASK],I.[FOTO],I.CANCELLATO, I.DATAMODIFICA, I.UTENTEMODIFICA,I.VERSIONE,I.STATO FROM INSERTED I
INNER JOIN DELETED D ON D.[IDSPSCHEDA]=I.[IDSPSCHEDA]

END
