
INSERT INTO BRANDS ( DESCRIZIONE, CANCELLATO, DATAMODIFICA, UTENTEMODIFICA) VALUES ( 'GUCCI', 0, GETDATE(),'IMPIANTO') 

INSERT INTO BRANDS ( DESCRIZIONE, CANCELLATO, DATAMODIFICA, UTENTEMODIFICA) VALUES ( 'YSL', 0, GETDATE(),'IMPIANTO') 

INSERT INTO BRANDS ( DESCRIZIONE, CANCELLATO, DATAMODIFICA, UTENTEMODIFICA) VALUES ( 'MC QUEEN', 0, GETDATE(),'IMPIANTO') 

INSERT INTO BRANDS ( DESCRIZIONE, CANCELLATO, DATAMODIFICA, UTENTEMODIFICA) VALUES ( 'LOUIS VUITTON', 0, GETDATE(),'IMPIANTO') 

INSERT INTO BRANDS ( DESCRIZIONE, CANCELLATO, DATAMODIFICA, UTENTEMODIFICA) VALUES ( 'FENDI', 0, GETDATE(),'IMPIANTO') 

