
CREATE TABLE TIPIDOCUMENTO
(
	IDTIPODOCUMENTO INT IDENTITY(1,1),
	DESCRIZIONE NVARCHAR(20) NOT NULL,
	CARTELLA NVARCHAR(10) NOT NULL,
	CANCELLATO	BIT NOT NULL,
	DATAMODIFICA	DATETIME NOT NULL,
	UTENTEMODIFICA	NVARCHAR(50) NOT NULL,
	 CONSTRAINT PK_IDTIPODOCUMENTO PRIMARY KEY (IDTIPODOCUMENTO)
)
GO
CREATE INDEX IDX_IDTIPODOCUMENTO_1 ON TIPIDOCUMENTO(DESCRIZIONE)

GO
CREATE TABLE TIPIDOCUMENTO_LOG
(
	IDTIPODOCUMENTO INT NULL,
	DESCRIZIONE NVARCHAR(20)NULL,
	CARTELLA NVARCHAR(10) NULL,
	CANCELLATO	BIT  NULL,
	DATAMODIFICA	DATETIME NULL,
	UTENTEMODIFICA	NVARCHAR(50) NULL
)
GO
CREATE OR ALTER TRIGGER TIPIDOCUMENTO_LOG_I
ON TIPIDOCUMENTO
AFTER INSERT
AS
BEGIN 
INSERT INTO TIPIDOCUMENTO_LOG (IDTIPODOCUMENTO, DESCRIZIONE,CARTELLA, CANCELLATO, DATAMODIFICA, UTENTEMODIFICA) 
SELECT I.IDTIPODOCUMENTO, I.DESCRIZIONE,I.CARTELLA, I.CANCELLATO, I.DATAMODIFICA, I.UTENTEMODIFICA FROM INSERTED I
END
GO


GO
CREATE OR ALTER TRIGGER TIPIDOCUMENTO_LOG_U
ON TIPIDOCUMENTO
AFTER UPDATE
AS
BEGIN 
INSERT INTO TIPIDOCUMENTO_LOG (IDTIPODOCUMENTO, DESCRIZIONE,CARTELLA, CANCELLATO, DATAMODIFICA, UTENTEMODIFICA) 
SELECT I.IDTIPODOCUMENTO, I.DESCRIZIONE,I.CARTELLA, I.CANCELLATO, I.DATAMODIFICA, I.UTENTEMODIFICA FROM TIPIDOCUMENTO I
INNER JOIN DELETED D ON D.IDTIPODOCUMENTO=I.IDTIPODOCUMENTO
END
GO



 CREATE TABLE DOCUMENTI
   (	
	IDDOCUMENTO INT IDENTITY(1,1),
	 IDTIPODOCUMENTO INT NOT NULL ,
	[FILENAME] NVARCHAR(50) NULL,
	ESTENSIONE NVARCHAR(10) NULL,
	DATI VARBINARY(MAX) NOT NULL,
	IDESTERNA INT NULL,
	TABELLAESTERNA	NVARCHAR(20) NOT NULL,
	CANCELLATO	BIT  NULL,
	DATAMODIFICA	DATETIME NULL,
	UTENTEMODIFICA	NVARCHAR(50) NULL      
	FOREIGN KEY (IDTIPODOCUMENTO) REFERENCES TIPIDOCUMENTO (IDTIPODOCUMENTO) ,
	 CONSTRAINT PK_IDDOCUMENTO PRIMARY KEY (IDDOCUMENTO)
   );

   CREATE UNIQUE INDEX IDX_DOCUMENTI_1 ON DOCUMENTI ([FILENAME])

 CREATE TABLE DOCUMENTI_LOG
   (	
	IDDOCUMENTO INT null,
	 IDTIPODOCUMENTO INT  NULL ,
	[FILENAME] NVARCHAR(50) NULL,
	ESTENSIONE NVARCHAR(10) NULL,
	DATI VARBINARY(MAX) NULL,
	IDESTERNA INT NULL,
	TABELLAESTERNA	NVARCHAR(20) NULL,
	CANCELLATO	BIT  NULL,
	DATAMODIFICA	DATETIME NULL,
	UTENTEMODIFICA	NVARCHAR(50) NULL      
   );

   GO
CREATE OR ALTER TRIGGER DOCUMENTI_LOG_I
ON DOCUMENTI
AFTER INSERT
AS
BEGIN 
INSERT INTO DOCUMENTI_LOG (IDDOCUMENTO, IDTIPODOCUMENTO,[FILENAME],ESTENSIONE,DATI,IDESTERNA,TABELLAESTERNA, CANCELLATO, DATAMODIFICA, UTENTEMODIFICA) 
SELECT I.IDDOCUMENTO, I.IDTIPODOCUMENTO,I.[FILENAME],I.ESTENSIONE,I.DATI,I.IDESTERNA,i.TABELLAESTERNA, I.CANCELLATO, I.DATAMODIFICA, I.UTENTEMODIFICA FROM INSERTED I
END

GO
CREATE OR ALTER TRIGGER DOCUMENTI_LOG_U
ON DOCUMENTI
AFTER UPDATE
AS
BEGIN 
INSERT INTO DOCUMENTI_LOG (IDDOCUMENTO, IDTIPODOCUMENTO,[FILENAME],ESTENSIONE,DATI,IDESTERNA,TABELLAESTERNA, CANCELLATO, DATAMODIFICA, UTENTEMODIFICA) 
SELECT I.IDDOCUMENTO, I.IDTIPODOCUMENTO,I.[FILENAME],I.ESTENSIONE,I.DATI,I.IDESTERNA,i.TABELLAESTERNA, I.CANCELLATO, I.DATAMODIFICA, I.UTENTEMODIFICA FROM DOCUMENTI I
INNER JOIN DELETED D ON D.IDDOCUMENTO = I.IDDOCUMENTO
END
GO

CREATE TABLE BLOCCHIDOCUMENTO
(
	IDBLOCCO INT IDENTITY(1,1),
	IDDOCUMENTO INT NOT NULL,
	ATTIVO BIT NOT NULL,
	TIPOBLOCCO NVARCHAR(20) NULL,
	INIZIOBLOCCO DATETIME NOT NULL,
	UTENTEINIZIO NVARCHAR(50) NOT NULL,
	FINEBLOCCO DATETIME NULL,
	UTENTEFINE NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_IDBLOCCO PRIMARY KEY (IDBLOCCO),
	FOREIGN KEY (IDDOCUMENTO) REFERENCES DOCUMENTI (IDDOCUMENTO) ,
)
GO


CREATE INDEX IDX_BLOCCHIDOCUMENTO_1 ON BLOCCHIDOCUMENTO(IDDOCUMENTO);


