USE [MPI]
GO

INSERT INTO [dbo].[TIPIDOCUMENTO]([DESCRIZIONE],[CARTELLA],[CANCELLATO],[DATAMODIFICA],[UTENTEMODIFICA])     VALUES('DISEGNO TECNICO 2D','D2D',0,GETDATE(),'IMPIANTO')
INSERT INTO [dbo].[TIPIDOCUMENTO]([DESCRIZIONE],[CARTELLA],[CANCELLATO],[DATAMODIFICA],[UTENTEMODIFICA])     VALUES('DISEGNO TECNICO 3D','D3D',0,GETDATE(),'IMPIANTO')
INSERT INTO [dbo].[TIPIDOCUMENTO]([DESCRIZIONE],[CARTELLA],[CANCELLATO],[DATAMODIFICA],[UTENTEMODIFICA])     VALUES('MODELLAZIONE','MOD',0,GETDATE(),'IMPIANTO')
INSERT INTO [dbo].[TIPIDOCUMENTO]([DESCRIZIONE],[CARTELLA],[CANCELLATO],[DATAMODIFICA],[UTENTEMODIFICA])     VALUES('CAPITOLATO','CAPITOLATO',0,GETDATE(),'IMPIANTO')
GO

